apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260517-014610-rpdlwgqea1pl-service
spec:
  selector:
    app: enterprise-system-20260517-014610-rpdlwgqea1pl
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
